# Generated by Django 5.2.7 on 2025-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField()),
                ('disciplinas', models.ManyToManyField(blank=True, to='app.disciplina', verbose_name='Disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='SisProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turmas', models.ManyToManyField(blank=True, to='app.professor', verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('sala', models.CharField(max_length=100)),
                ('disciplinas', models.ManyToManyField(blank=True, to='app.disciplina', verbose_name='Disciplinas')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='app.turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField()),
                ('r_nome', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('r_email', models.EmailField(max_length=254, verbose_name='E-mail do Responsável')),
                ('r_telefone', models.CharField(verbose_name='Telefone do Responsável')),
                ('turmas', models.ManyToManyField(blank=True, to='app.turma', verbose_name='Turma')),
            ],
        ),
    ]
